source: /app/
collections_config:
  pages:
    path: ''
    name: Pages
    icon: wysiwyg
  drafts:
    path: _drafts
    name: Drafts
    icon: event
    create:
      path: ''
      publish_to: posts
    _inputs:
      categories:
        type: multiselect
        options:
          values: collections.posts[*].categories
          allow_create: true
      tags:
        type: multiselect
        options:
          values: collections.posts[*].tags
          allow_create: true
  events:
    path: _events
    name: Events
    icon: event
  our_work:
    path: _our_work
    name: Our Work
    icon: group_work
  posts:
    path: _posts
    name: Posts
    icon: event_available
    create:
      path: >-
        [relative_base_path]/{date|year}-{date|month}-{date|day}-{title|slugify}.[ext]
    _inputs:
      categories:
        type: multiselect
        options:
          values: collections.posts[*].categories
          allow_create: true
      tags:
        type: multiselect
        options:
          values: collections.posts[*].tags
          allow_create: true
    add_options:
      - name: Add Post
      - name: Add Draft
        collection: drafts
  data:
    path: _data
    name: Data
    icon: data_usage
    disable_url: true
    disable_add: true
    disable_add_folder: true
    disable_file_actions: true
  jobs:
    path: _jobs
    name: Jobs
    icon: sos
    disable_url: true
  our_work_pageless:
    path: _our_work_pageless
    name: Our Work Pageless
    icon: workspaces
    disable_url: true
paths:
  static: ''
  uploads: uploads
timezone: America/New_York
markdown:
  engine: kramdown
  options:
    heading_ids: false
    gfm: false
    breaks: false
    typographer: false
    attributes: true
    attribute_elements:
      inline: right
      block: below
      tr: none
      td: none
      li: right-of-prefix
    treat_indentation_as_code: true
_snippets_imports:
  jekyll: true
